#!/bin/bash
# .claude/hooks/pre-prompt.sh
# Pre-hook: Detects JIRA_STORIES in prompt, fetches Jira details, writes context file.
# Runs before every tool use — exits silently if not a Jira workflow prompt.

set -e

JIRA_CLI="C:/Users/suryathota/tools/jira-cli"
JIRA_SPEC="C:/Users/suryathota/tools/jira-cli_SPEC.md.txt"
CONTEXT_FILE=".claude/jira-context.md"
PROMPT_CACHE=".claude/.last-prompt.txt"

# ── Read the incoming prompt from stdin (Claude passes it as JSON) ──────────
HOOK_INPUT=$(cat)
PROMPT=$(echo "$HOOK_INPUT" | grep -o '"prompt":"[^"]*"' | head -1 | sed 's/"prompt":"//;s/"$//')

# ── Only activate for JIRA_STORIES prompts ──────────────────────────────────
if ! echo "$PROMPT" | grep -qi "JIRA_STORIES:"; then
  exit 0
fi

echo "[HOOK] JIRA_STORIES detected — starting pre-hook" >&2

# ── Extract Jira IDs (comma-separated after JIRA_STORIES:) ──────────────────
JIRA_LINE=$(echo "$PROMPT" | grep -i "JIRA_STORIES:" | head -1)
JIRA_IDS_RAW=$(echo "$JIRA_LINE" | sed 's/.*JIRA_STORIES://I' | tr ',' '\n' | tr -d ' ' | grep -v '^$')

if [ -z "$JIRA_IDS_RAW" ]; then
  echo "[HOOK][ERROR] Could not extract Jira IDs from prompt. Aborting." >&2
  exit 1
fi

echo "[HOOK] Jira IDs found:" >&2
echo "$JIRA_IDS_RAW" >&2

# ── Validate & fetch each Jira story ────────────────────────────────────────
mkdir -p .claude

{
  echo "# Jira Story Context"
  echo "_Generated by pre-hook on $(date)_"
  echo ""
} > "$CONTEXT_FILE"

FETCH_FAILED=0
FIRST_ID=""

while IFS= read -r JIRA_ID; do
  [ -z "$JIRA_ID" ] && continue
  [ -z "$FIRST_ID" ] && FIRST_ID="$JIRA_ID"

  echo "[HOOK] Fetching: $JIRA_ID" >&2

  # Call jira-cli to get issue details
  # Adjust the command below to match your jira-cli_SPEC.md.txt syntax
  JIRA_OUTPUT=$("$JIRA_CLI" issue view "$JIRA_ID" 2>&1) || {
    echo "[HOOK][ERROR] Failed to fetch $JIRA_ID — is it a valid Jira ID?" >&2
    FETCH_FAILED=1
    continue
  }

  {
    echo "## $JIRA_ID"
    echo ""
    echo "$JIRA_OUTPUT"
    echo ""
    echo "---"
    echo ""
  } >> "$CONTEXT_FILE"

  echo "[HOOK] ✅ Fetched: $JIRA_ID" >&2

done <<< "$JIRA_IDS_RAW"

if [ "$FETCH_FAILED" -eq 1 ]; then
  echo "[HOOK][ERROR] One or more Jira stories could not be fetched. Check IDs and Jira connectivity." >&2
  exit 1
fi

# ── Count IDs and decide branch name ────────────────────────────────────────
JIRA_COUNT=$(echo "$JIRA_IDS_RAW" | grep -c '.')

if [ "$JIRA_COUNT" -eq 1 ]; then
  BRANCH_NAME="feature/${FIRST_ID}"
else
  BRANCH_NAME="feature/${FIRST_ID}-multi"
fi

# ── Append branch suggestion to context file ────────────────────────────────
{
  echo "## Branch Info"
  echo ""
  echo "- Total stories: $JIRA_COUNT"
  echo "- Suggested branch: \`$BRANCH_NAME\`"
  echo "- Base branch: \`develop\`"
  echo ""
} >> "$CONTEXT_FILE"

echo "[HOOK] Context written to $CONTEXT_FILE" >&2
echo "[HOOK] Suggested branch: $BRANCH_NAME" >&2
echo "[HOOK] ✅ Pre-hook complete. Claude will now take over." >&2

exit 0
