# #!/bin/bash
# # .claude/hooks/pre-prompt.sh
# # Pre-hook: Detects JIRA_STORIES in prompt, fetches Jira details, writes context file.
# # Runs before every tool use — exits silently if not a Jira workflow prompt.

# set -e

# JIRA_CLI="C:/Users/suryathota/tools/jira-cli"
# JIRA_SPEC="C:/Users/suryathota/tools/jira-cli_SPEC.md.txt"
# CONTEXT_FILE=".claude/jira-context.md"
# PROMPT_CACHE=".claude/.last-prompt.txt"

# # ── Read the incoming prompt from stdin (Claude passes it as JSON) ──────────
# HOOK_INPUT=$(cat)
# PROMPT=$(echo "$HOOK_INPUT" | grep -o '"prompt":"[^"]*"' | head -1 | sed 's/"prompt":"//;s/"$//')

# # ── Only activate for JIRA_STORIES prompts ──────────────────────────────────
# if ! echo "$PROMPT" | grep -qi "JIRA_STORIES:"; then
#   exit 0
# fi

# echo "[HOOK] JIRA_STORIES detected — starting pre-hook" >&2

# # ── Extract Jira IDs (comma-separated after JIRA_STORIES:) ──────────────────
# JIRA_LINE=$(echo "$PROMPT" | grep -i "JIRA_STORIES:" | head -1)
# JIRA_IDS_RAW=$(echo "$JIRA_LINE" | sed 's/.*JIRA_STORIES://I' | tr ',' '\n' | tr -d ' ' | grep -v '^$')

# if [ -z "$JIRA_IDS_RAW" ]; then
#   echo "[HOOK][ERROR] Could not extract Jira IDs from prompt. Aborting." >&2
#   exit 1
# fi

# echo "[HOOK] Jira IDs found:" >&2
# echo "$JIRA_IDS_RAW" >&2

# # ── Validate & fetch each Jira story ────────────────────────────────────────
# mkdir -p .claude

# {
#   echo "# Jira Story Context"
#   echo "_Generated by pre-hook on $(date)_"
#   echo ""
# } > "$CONTEXT_FILE"

# FETCH_FAILED=0
# FIRST_ID=""

# while IFS= read -r JIRA_ID; do
#   [ -z "$JIRA_ID" ] && continue
#   [ -z "$FIRST_ID" ] && FIRST_ID="$JIRA_ID"

#   echo "[HOOK] Fetching: $JIRA_ID" >&2

#   # Call jira-cli to get issue details
#   # Adjust the command below to match your jira-cli_SPEC.md.txt syntax
#   JIRA_OUTPUT=$("$JIRA_CLI" issue view "$JIRA_ID" 2>&1) || {
#     echo "[HOOK][ERROR] Failed to fetch $JIRA_ID — is it a valid Jira ID?" >&2
#     FETCH_FAILED=1
#     continue
#   }

#   {
#     echo "## $JIRA_ID"
#     echo ""
#     echo "$JIRA_OUTPUT"
#     echo ""
#     echo "---"
#     echo ""
#   } >> "$CONTEXT_FILE"

#   echo "[HOOK] ✅ Fetched: $JIRA_ID" >&2

# done <<< "$JIRA_IDS_RAW"

# if [ "$FETCH_FAILED" -eq 1 ]; then
#   echo "[HOOK][ERROR] One or more Jira stories could not be fetched. Check IDs and Jira connectivity." >&2
#   exit 1
# fi

# # ── Count IDs and decide branch name ────────────────────────────────────────
# JIRA_COUNT=$(echo "$JIRA_IDS_RAW" | grep -c '.')

# if [ "$JIRA_COUNT" -eq 1 ]; then
#   BRANCH_NAME="feature/${FIRST_ID}"
# else
#   BRANCH_NAME="feature/${FIRST_ID}-multi"
# fi

# # ── Append branch suggestion to context file ────────────────────────────────
# {
#   echo "## Branch Info"
#   echo ""
#   echo "- Total stories: $JIRA_COUNT"
#   echo "- Suggested branch: \`$BRANCH_NAME\`"
#   echo "- Base branch: \`develop\`"
#   echo ""
# } >> "$CONTEXT_FILE"

# echo "[HOOK] Context written to $CONTEXT_FILE" >&2
# echo "[HOOK] Suggested branch: $BRANCH_NAME" >&2
# echo "[HOOK] ✅ Pre-hook complete. Claude will now take over." >&2

# exit 0



#!/bin/bash
# .claude/hooks/pre-prompt.sh
# Pre-hook: Detects JIRA_STORIES in prompt, fetches Jira details, writes context file.
# Claude Code injects env vars from settings.json automatically.

JIRA_CLI="C:/Users/suryathota/tools/jira-cli"
CONTEXT_FILE=".claude/jira-context.md"

# ── Read full stdin (Claude passes hook input as JSON) ──────────────────────
HOOK_INPUT=$(cat)

# ── Write raw input to a temp file so we can parse it safely ────────────────
TMPFILE=$(mktemp /tmp/hook-input-XXXX.json)
echo "$HOOK_INPUT" > "$TMPFILE"

# ── Extract prompt — handles multiline by using python-safe approach via awk ─
# Try to extract the full prompt text from the JSON
PROMPT=$(echo "$HOOK_INPUT" | tr -d '\n' | grep -o '"prompt":"[^"]*"' | sed 's/"prompt":"//;s/"$//')

# Fallback: dump entire input and search for JIRA_STORIES anywhere in it
if ! echo "$HOOK_INPUT" | grep -qi "JIRA_STORIES"; then
  rm -f "$TMPFILE"
  exit 0
fi

echo "[HOOK] JIRA_STORIES detected — starting pre-hook" >&2

# ── Validate required env vars ───────────────────────────────────────────────
MISSING=0
for VAR in JIRA_BASE_URL JIRA_API_TOKEN BITBUCKET_BASE_URL BITBUCKET_API_TOKEN BITBUCKET_PROJECT BITBUCKET_REPO; do
  if [ -z "${!VAR}" ]; then
    echo "[HOOK][ERROR] $VAR is not set in .claude/settings.json env block" >&2
    MISSING=1
  fi
done

if [ "$MISSING" -eq 1 ]; then
  echo "[HOOK][ERROR] Fill in missing values in .claude/settings.json and retry." >&2
  rm -f "$TMPFILE"
  exit 1
fi

echo "[HOOK] ✅ All env vars present" >&2

# ── Extract Jira IDs ─────────────────────────────────────────────────────────
JIRA_LINE=$(echo "$HOOK_INPUT" | tr -d '\n' | grep -oi 'JIRA_STORIES:[^"\\]*' | head -1)
JIRA_IDS_RAW=$(echo "$JIRA_LINE" | sed 's/JIRA_STORIES://I' | tr ',' '\n' | tr -d ' \t\r\\n' | grep -v '^$')

if [ -z "$JIRA_IDS_RAW" ]; then
  echo "[HOOK][ERROR] Could not extract Jira IDs. Make sure format is: JIRA_STORIES: PROJ-123, PROJ-124" >&2
  rm -f "$TMPFILE"
  exit 1
fi

echo "[HOOK] IDs found: $(echo $JIRA_IDS_RAW | tr '\n' ' ')" >&2

# ── Create context file ──────────────────────────────────────────────────────
mkdir -p .claude

{
  echo "# Jira Story Context"
  echo "_Generated: $(date)_"
  echo ""
  echo "- Jira URL: $JIRA_BASE_URL"
  echo "- Bitbucket Project: $BITBUCKET_PROJECT / Repo: $BITBUCKET_REPO"
  echo ""
} > "$CONTEXT_FILE"

FETCH_FAILED=0
FIRST_ID=""
JIRA_COUNT=0

while IFS= read -r JIRA_ID; do
  [ -z "$JIRA_ID" ] && continue
  [ -z "$FIRST_ID" ] && FIRST_ID="$JIRA_ID"
  JIRA_COUNT=$((JIRA_COUNT + 1))

  echo "[HOOK] Fetching: $JIRA_ID ..." >&2

  # ── Adjust flags below to match your jira-cli_SPEC.md.txt ──────────────
  JIRA_OUTPUT=$("$JIRA_CLI" issue view "$JIRA_ID" \
    --url "$JIRA_BASE_URL" \
    --token "$JIRA_API_TOKEN" 2>&1)
  EXIT_CODE=$?

  if [ $EXIT_CODE -ne 0 ]; then
    echo "[HOOK][ERROR] Failed to fetch $JIRA_ID (exit $EXIT_CODE)" >&2
    echo "[HOOK][ERROR] Output: $JIRA_OUTPUT" >&2
    FETCH_FAILED=1
    continue
  fi

  {
    echo "## $JIRA_ID"
    echo ""
    echo "$JIRA_OUTPUT"
    echo ""
    echo "---"
    echo ""
  } >> "$CONTEXT_FILE"

  echo "[HOOK] ✅ Fetched: $JIRA_ID" >&2

done <<< "$JIRA_IDS_RAW"

if [ "$FETCH_FAILED" -eq 1 ]; then
  echo "[HOOK][ERROR] One or more stories failed to fetch. Aborting." >&2
  rm -f "$TMPFILE"
  exit 1
fi

# ── Branch name ──────────────────────────────────────────────────────────────
if [ "$JIRA_COUNT" -eq 1 ]; then
  BRANCH_NAME="feature/${FIRST_ID}"
else
  BRANCH_NAME="feature/${FIRST_ID}-multi"
fi

{
  echo "## Branch Info"
  echo "- Stories: $JIRA_COUNT"
  echo "- Branch: \`$BRANCH_NAME\`"
  echo "- Base: \`develop\`"
  echo "- Bitbucket URL: $BITBUCKET_BASE_URL"
  echo ""
} >> "$CONTEXT_FILE"

echo "[HOOK] ✅ Context written to $CONTEXT_FILE" >&2
echo "[HOOK] ✅ Branch: $BRANCH_NAME" >&2
echo "[HOOK] ✅ Pre-hook complete — Claude will now proceed." >&2

rm -f "$TMPFILE"
exit 0

# ── SAFETY GUARD: Block destructive Bitbucket operations ────────────────────
# This function should be called before any bitbucket-cli command
validate_bitbucket_command() {
  local CMD="$1"
  local DESTRUCTIVE_PATTERNS="delete|remove|destroy|drop|purge|wipe|truncate|force-delete|force-push|--force|-D"
  
  if echo "$CMD" | grep -qiE "$DESTRUCTIVE_PATTERNS"; then
    echo "[HOOK][BLOCKED] Destructive Bitbucket command detected and blocked: $CMD" >&2
    echo "[HOOK][BLOCKED] Claude is not allowed to delete branches, repos, or any Bitbucket resources." >&2
    exit 1
  fi
}
